const proyectos = [
  {
    titulo: "Pagina Web Centro de Varones",
    descripcion: "Esta Pagina Web Fue Creada para Centro De Varones Para Tener Mas Informados A Los Padres De Familia Como Tambien Podemos Tener de Alumnos",
    creadores: "esta web se trabajo primero en 4 personas luego este se a reducido hasta que solo fui el unico que lo acabo",
    link: "https://www.youtube.com/watch?v=-IK4olKRqZY&t=18s",
    proceso_automatizacion: "web_youtube_pagina.png",
    fecha: "01/12/2023",
    imagen: "web_youtube_pagina.png",
    tecnologias: ["Javascript", "HTML", "CSS", "BD (MYSQL)", "Express", "NodeJS"],
  },
  {
    titulo: "Reserva de Citas Para MachaBarberShop",
    descripcion: "Fue Un sistema para administrar todo el procedimiento que hace barberia venta ,pagos a barberos , etc",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://youtu.be/MRFVRMbrroE?si=1qGUru3J93pjRk19",
    proceso_automatizacion: "citas.png",
    fecha: "01/12/2023",
    imagen: "citas.png",
    tecnologias: ["Javascript", "HTML", "CSS", "BD (SQLSERVER)", "JAVA(JAKARTA)", "DOCKER"],
  },
  {
    titulo: "Juego De Mini Micraft",
    descripcion: "Fue A Base De Un tutorial Que Me Pude Ver en Youtube",
    creadores: "bueno el credito yo le daria al video de youtube que mire yo despues solo quise agregarles un poco mas pero es un interesante proyecto",
    link: "https://github.com/Omarrivv/juegoMiniMicraft.git",
    proceso_automatizacion: "pythonminicraft.png",
    fecha: "01/06/2023",
    imagen: "fondo-python.png",
    tecnologias: ["Python", "Librerias de Python"],
  },
  {
    titulo: "Automatización de Envíos por Email usando Google Apps Script",
    descripcion: "En este video, te sumergirás en el fascinante mundo de la automatización con Google Apps Script. Descubre cómo puedes simplificar tareas repetitivas y ahorrar tiempo utilizando la potencia de la automatización.",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://youtu.be/mv5Ns-YKezs?si=EGKYGe2sPEqkK9H1",
    proceso_automatizacion: "image.png",
    fecha: "02/02/2024",
    imagen: "image.png",
    tecnologias: ["Google Apps Script", "Sheets", "Forms"],
  },
  {
    titulo: "Escraedor de videos de Youtube",
    descripcion: "Este es un escraedor educativo con librerias de python (pytube) ...",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://youtu.be/-b_KbTlfR8k?si=n23Jhv9C-gXPn2GH",
    proceso_automatizacion: "you-extraedorvideos.png",
    fecha: "02/02/2024",
    imagen: "you-extraedorvideos.png",
    tecnologias: ["python", "Flask", "librerias de Python"],
  },
  {
    titulo: "Aprende Contabilidad Básica",
    descripcion: "Domina los conceptos fundamentales de la ecuación contable",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://contabilidadv1.netlify.app/",
    proceso_automatizacion: "contabilidad.png",
    fecha: "27/08/2025",
    imagen: "contabilidad.png",
    tecnologias: ["HTML", "CSS", "JAVASCRIPT"],
  },
  {
    titulo: "🛒 CryptoStore",
    descripcion: "Compra productos exclusivos con Ethereum (Metamask Red de Prueba)",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://etherium-v1.netlify.app/",
    proceso_automatizacion: "crypto.png",
    fecha: "27/08/2025",
    imagen: "crypto.png",
    tecnologias: ["HTML", "CSS", "JAVASCRIPT"],
  },
  {
    titulo: "alquiler-espacios",
    descripcion: "Encuentra el espacio perfecto para tu evento Alquila salas de reuniones, oficinas, salones de eventos y más. Reserva fácilmente y paga de forma segura.",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://alquiler-espacios.netlify.app/",
    proceso_automatizacion: "alquiler_espacios.png",
    fecha: "27/08/2025",
    imagen: "alquiler_espacios.png",
    tecnologias: ["HTML", "CSS", "JAVASCRIPT","NODEJS","RENDER PLATAFORMA BACKEND"],
  },
  {
    titulo: "Manejador de Operaciones personales",
    descripcion: "Maneja tus operaciones personales gastos ingresos metas de ahorro",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://operaciones-personales.netlify.app/",
    proceso_automatizacion: "operaciones_personales.png",
    fecha: "27/08/2025",
    imagen: "operaciones_personales.png",
    tecnologias: ["HTML", "CSS", "JAVASCRIPT","NODEJS"],
  },
  {
    titulo: "Sitio Web Macha Barbershop",
    descripcion: "Sitio Web Compra de Productos de la barberia",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://machashopv.netlify.app/",
    proceso_automatizacion: "machashop.png",
    fecha: "27/08/2025",
    imagen: "machashop.png",
    tecnologias: ["HTML", "CSS", "JAVASCRIPT"],
  },
  {
    titulo: "Encomerce Demo Tienda Propia",
    descripcion: "Sitio Web Compra de Productos Demo",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://encomerseomarcode.netlify.app/",
    proceso_automatizacion: "encomerce.png",
    fecha: "27/08/2025",
    imagen: "encomerce.png",
    tecnologias: ["ANGULAR"],
  },
  {
    titulo: " Sistema de Gestión de Productos",
    descripcion: "Gestiona tus productos, costos y ganancias de manera eficiente",
    creadores: "OMAR FELIX RIVERA ROSAS",
    link: "https://encomerseomarcode.netlify.app/",
    proceso_automatizacion: "gestion_productos.png",
    fecha: "27/08/2025",
    imagen: "gestion_productos.png",
    tecnologias: ["HTML","CSS","JAVASCRIPT"],
  }
];

const informacionPersonal = {
  nombre: "Omar Felix Rivera Rosas",
  subtitulo: "Desarrollador Backend Y Frontend 🤖➡️⬆️",
  imagen: "/img/portadopor.png",
  otros: [
    ["Nacionalidad", "Peruano"],
    [
      "Edad",
      new Date(new Date() - new Date("2005/12/02")).getFullYear() - 1970 + " años",
    ],
  ],
  idiomas: [
    ["Español", "Nativo"],
    ["Inglés", "Basico"],
  ],
  tecnologias: [
    ["Python", 10],
    ["JavaScript", 9],
    ["Css", 9],
    ["Typescript", 6],
    ["Angular", 5],
    ["Linux", 7],
    ["NodeJS", 7],
    ["HTML", 9],
    ["AWS", 6],
    ["Java", 5],
    ['Docker', 5],
    ['Git', 5],
    ['MySql', 5],
    ['SQLSERVER', 5],
  ],
  redes: [
    ["github", "https://github.com/Omarrivv"],
    ["linkedin", "https://www.linkedin.com/in/omar-felix-rivera-rosas-149619274/"],
    ["youtube", "https://www.youtube.com/@codefxomarroma"],
    ["instagram", "https://www.youtube.com/@codefxomarroma"],
    ["facebook", "https://www.facebook.com/omarfelix.riverarosas/"],
  ]
}; 